# Generated by Django 5.0.4 on 2024-05-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('periodo', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('opciones', models.TextField()),
                ('respuesta', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioPregunta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.cuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('ultimaActualizacion', models.DateTimeField(auto_now=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.cuestionario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipoPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.tipopregunta'),
        ),
    ]
